In [1]:
import pandas as pd
import matplotlib.pyplot as pp
import numpy as np
import seaborn as sns
import os
from urllib.request import urlopen, Request
import requests as r
from sys import argv, exit
from base64 import b64encode
import json
import re

from dotenv import load_dotenv, find_dotenv
dotenv_path=find_dotenv()
load_dotenv(dotenv_path)
client_id= os.environ.get('SPOTIFY_CLIENT_ID')
client_secret= os.environ.get('SPOTIFY_CLIENT_SECRET')

import spotipy
import sys
from sys import argv, exit
from spotipy.oauth2 import SpotifyClientCredentials

#Authentication without user
client_credentials_manager= SpotifyClientCredentials(client_id= client_id, client_secret=client_secret)
sp= spotipy.Spotify(client_credentials_manager=client_credentials_manager)

In [2]:
client_secret

'b80b9ffa98cf4967903f4c159377244c'

In [3]:
kpop_00_data= pd.read_csv('/Users/josephlim/Downloads/KPopHits2000.csv')
kpop_21_data=pd.read_csv('/Users/josephlim/Downloads/KPopHits2021.csv')
df_US20=pd.read_csv('/Users/josephlim/Downloads/songs_normalize.csv')
df_US21= pd.read_csv('/Users/josephlim/Downloads/spotify-charts.csv')
# US data didn't have features we were after

In [4]:
kpop_00_data.isna().any()

Unnamed: 0        False
title             False
artist/s          False
danceability      False
energy            False
key               False
loudness          False
mode              False
speechiness       False
acousticness      False
valence           False
tempo             False
duration_ms       False
time_signature    False
dtype: bool

In [5]:
kpop_21_data.isna().any()

Unnamed: 0        False
title             False
artist/s          False
danceability      False
energy            False
key               False
loudness          False
mode              False
speechiness       False
acousticness      False
valence           False
tempo             False
duration_ms       False
time_signature    False
dtype: bool

In [6]:
df_US21.isna().any()

Unnamed: 0           False
Position             False
Track Name           False
Streams              False
Chart Start Date     False
Chart End Date       False
Album Name           False
Release Date         False
Artist               False
Features             False
Song Duration(ms)    False
Explicit             False
Url                  False
dtype: bool

In [7]:
df_US20.isna().any()

artist              False
song                False
duration_ms         False
explicit            False
year                False
popularity          False
danceability        False
energy              False
key                 False
loudness            False
mode                False
speechiness         False
acousticness        False
instrumentalness    False
liveness            False
valence             False
tempo               False
genre               False
dtype: bool

In [8]:
kpop_00_data.describe()

,Unnamed: 0,danceability,energy,key,loudness,mode,speechiness,acousticness,valence,tempo,duration_ms,time_signature
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,14.500000,0.605633,0.676100,4.233333,-6.617667,0.566667,0.058683,0.239880,0.545703,127.925267,242037.000000,3.966667
std,8.803408,0.155947,0.213711,3.793673,3.568555,0.504007,0.040504,0.264849,0.280608,25.270631,54347.072547,0.182574
min,0.000000,0.330000,0.233000,0.000000,-15.467000,0.000000,0.026900,0.000427,0.082100,74.692000,48248.000000,3.000000
25%,7.250000,0.474000,0.530750,0.000000,-7.800500,0.000000,0.034425,0.028625,0.250000,118.443750,215259.250000,4.000000
50%,14.500000,0.631500,0.736500,3.500000,-6.134500,1.000000,0.042150,0.118000,0.656500,132.017000,236705.500000,4.000000
75%,21.750000,0.729000,0.833000,8.000000,-4.090250,1.000000,0.066825,0.405250,0.733500,142.283500,260552.250000,4.000000
max,29.000000,0.838000,0.997000,9.000000,-1.820000,1.000000,0.180000,0.913000,0.971000,179.482000,340907.000000,4.000000

In [9]:
kpop_21_data.describe()

,Unnamed: 0,danceability,energy,key,loudness,mode,speechiness,acousticness,valence,tempo,duration_ms,time_signature
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.0
mean,24.50000,0.681860,0.787920,5.280000,-3.790740,0.620000,0.089900,0.097556,0.577220,126.758600,197322.080000,4.0
std,14.57738,0.117991,0.127271,3.779861,1.976335,0.490314,0.053693,0.123401,0.192103,27.460848,20728.437265,0.0
min,0.00000,0.311000,0.377000,0.000000,-10.121000,0.000000,0.035100,0.000707,0.135000,61.450000,149214.000000,4.0
25%,12.25000,0.609000,0.735750,1.250000,-5.040500,0.000000,0.054075,0.018575,0.445500,109.985750,184140.250000,4.0
50%,24.50000,0.690500,0.818500,6.000000,-3.593000,1.000000,0.076800,0.054650,0.638000,124.975500,195680.000000,4.0
75%,36.75000,0.765500,0.869750,9.000000,-2.230000,1.000000,0.103250,0.118500,0.721250,147.963250,212248.500000,4.0
max,49.00000,0.883000,0.963000,11.000000,-0.384000,1.000000,0.280000,0.594000,0.922000,188.700000,247360.000000,4.0

In [10]:
df_US21.describe()

        Unnamed: 0     Position  Song Duration(ms)
count  1260.000000  1260.000000        1260.000000
mean    629.500000    15.500000      198219.403175
std     363.874979     8.658878       38673.538380
min       0.000000     1.000000      121572.000000
25%     314.750000     8.000000      170813.000000
50%     629.500000    15.500000      199604.000000
75%     944.250000    23.000000      216258.250000
max    1259.000000    30.000000      383036.000000

In [11]:
df_US20.describe()

,duration_ms,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo
count,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,228748.124500,2009.49400,59.872500,0.667438,0.720366,5.378000,-5.512434,0.553500,0.103568,0.128955,0.015226,0.181216,0.551690,120.122558
std,39136.569008,5.85996,21.335577,0.140416,0.152745,3.615059,1.933482,0.497254,0.096159,0.173346,0.087771,0.140669,0.220864,26.967112
min,113000.000000,1998.00000,0.000000,0.129000,0.054900,0.000000,-20.514000,0.000000,0.023200,0.000019,0.000000,0.021500,0.038100,60.019000
25%,203580.000000,2004.00000,56.000000,0.581000,0.622000,2.000000,-6.490250,0.000000,0.039600,0.014000,0.000000,0.088100,0.386750,98.985750
50%,223279.500000,2010.00000,65.500000,0.676000,0.736000,6.000000,-5.285000,1.000000,0.059850,0.055700,0.000000,0.124000,0.557500,120.021500
75%,248133.000000,2015.00000,73.000000,0.764000,0.839000,8.000000,-4.167750,1.000000,0.129000,0.176250,0.000068,0.241000,0.730000,134.265500
max,484146.000000,2020.00000,89.000000,0.975000,0.999000,11.000000,-0.276000,1.000000,0.576000,0.976000,0.985000,0.853000,0.973000,210.851000

In [12]:
df_US21.head()

,Unnamed: 0,Position,Track Name,Streams,Chart Start Date,Chart End Date,Album Name,Release Date,Artist,Features,Song Duration(ms),Explicit,Url
0,0,1,Easy On Me by Adele,"57,081,735",2021-10-22,2021-10-29,Easy On Me,2021-10-14,Adele,None,224694,False,https://open.spotify.com/track/0gplL1WMoJ6iYaP...
1,1,2,STAY (with Justin Bieber) by The Kid LAROI,"43,772,708",2021-10-22,2021-10-29,F*CK LOVE 3: OVER YOU,2021-07-23,The Kid LAROI,Justin Bieber,141805,True,https://open.spotify.com/track/5PjdY0CKGZdEuoN...
2,2,3,INDUSTRY BABY (feat. Jack Harlow) by Lil Nas X,"38,131,363",2021-10-22,2021-10-29,MONTERO,2021-09-17,Lil Nas X,Jack Harlow,212352,True,https://open.spotify.com/track/5Z9KJZvQzH6PFmb...
3,3,4,Heat Waves by Glass Animals,"30,071,945",2021-10-22,2021-10-29,Dreamland (+ Bonus Levels),2020-08-06,Glass Animals,None,238805,False,https://open.spotify.com/track/02MWAaffLxlfxAU...
4,4,5,MONEY by LISA,"27,961,856",2021-10-22,2021-10-29,LALISA,2021-09-10,LISA,None,168227,False,https://open.spotify.com/track/7hU3IHwjX150XLo...

In [13]:
US21_feat= df_US21.loc[:,['Track Name','Artist','Url']]

In [14]:
US21_feat.columns

Index(['Track Name', 'Artist', 'Url'], dtype='object')

In [15]:
US21_feat['Url']

0       https://open.spotify.com/track/0gplL1WMoJ6iYaP...
1       https://open.spotify.com/track/5PjdY0CKGZdEuoN...
2       https://open.spotify.com/track/5Z9KJZvQzH6PFmb...
3       https://open.spotify.com/track/02MWAaffLxlfxAU...
4       https://open.spotify.com/track/7hU3IHwjX150XLo...
                              ...
1255    https://open.spotify.com/track/0E4Y1XIbs8GrAT1...
1256    https://open.spotify.com/track/3Uo7WG0vmLQ07WB...
1257    https://open.spotify.com/track/5QO79kh1waicV47...
1258    https://open.spotify.com/track/1yoMvmasuxZfqHE...
1259    https://open.spotify.com/track/4y4spB9m0Q6026K...
Name: Url, Length: 1260, dtype: object

In [16]:
US21_feat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Track Name  1260 non-null   object
 1   Artist      1260 non-null   object
 2   Url         1260 non-null   object
dtypes: object(3)
memory usage: 29.7+ KB

In [17]:
type(US21_feat)

pandas.core.frame.DataFrame

In [18]:

def get_auth_key():
    headers = {}
    client_id = ""
    client_secret = ""
    with open("client_id.txt", "r") as infile:
        client_id = infile.read()
        client_id = client_id[ 0 : len(client_id) - 1]
    with open("client_secret.txt", "r") as infile:
        client_secret = infile.read()
        client_secret = client_secret[ 0 : len(client_secret) - 1]
    client_str = f"{client_id}:{client_secret}"
    client_str_bytes = client_str.encode('ascii')
    client_str = b64encode( client_str_bytes ) 
    client_str = client_str.decode('ascii')
    auth_header = f"Basic {client_str}"
    headers['Authorization'] = auth_header
    data = {
        "grant_type" : "client_credentials"
    }
    url = "https://accounts.spotify.com/api/token"
    myreq = r.post(url, headers=headers, data=data)
    status_code = myreq.status_code 
    content = myreq.content.decode('ascii')
    json_data = json.loads(content)
    access_token = json_data['access_token']
    return access_token

In [19]:
access_token= get_auth_key()

In [20]:

def do_request(title, artist):
#     artist_name = argv[1]
#     print(artist_name)
    url = f"https://api.spotify.com/v1/search?q=track:{title}%20artist:{artist}&type=track,artist"
    
    headers = {
        "Accept"        : "application/json",
        "Content-Type"  : "application/json",
    }
    auth_key = get_auth_key()
    headers['Authorization'] = f"Bearer {auth_key}"
    myreq = r.get(url, headers=headers)
    content = myreq.content
    status_code = myreq.status_code 
    if status_code != 200:
        print("Error: status code:", status_code)
        exit(-1)
    json_data = json.loads(content)
    #json_str = json.dumps(json_data, indent=2)
    #print(json_str)
    return json_data

In [21]:
client_credentials_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

In [22]:
Track_Name= US21_feat['Track Name']
Artist= US21_feat['Artist']

In [23]:
for i in range(len(Track_Name)):
    words=list(Track_Name[i].split('by'))
    Track_Name[i]=words[0]

In [24]:
for i in range(len(Track_Name)):
    words=list(Track_Name[i].split('(with'))
    Track_Name[i]=words[0]

In [25]:
for i in range(len(Track_Name)):
    words=list(Track_Name[i].split('(feat.'))
    Track_Name[i]=words[0]

In [26]:
track_info=do_request('Easy On Me' , 'Adele')
sp.audio_features(track_info['tracks']['items'][0]['uri'])[0]

{'danceability': 0.604,
 'energy': 0.366,
 'key': 5,
 'loudness': -7.519,
 'mode': 1,
 'speechiness': 0.0282,
 'acousticness': 0.578,
 'instrumentalness': 0,
 'liveness': 0.133,
 'valence': 0.13,
 'tempo': 141.981,
 'type': 'audio_features',
 'id': '0gplL1WMoJ6iYaPgMCL0gX',
 'uri': 'spotify:track:0gplL1WMoJ6iYaPgMCL0gX',
 'track_href': 'https://api.spotify.com/v1/tracks/0gplL1WMoJ6iYaPgMCL0gX',
 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/0gplL1WMoJ6iYaPgMCL0gX',
 'duration_ms': 224695,
 'time_signature': 4}

In [ ]:
features={}
error_index=[]
for i in range(len(US21_feat)):
    try:
        track_info= do_request(Track_Name[i], Artist[i])
        features.update(sp.audio_features(track_info['tracks']['items'][0]['uri'])[0])
    except:
        error_index.append(i)
        
print("Error on:", error_index)

In [ ]:
for i in error_index:
    print(f"Track {i}:",Track_Name[i])
    print(f"Artist {i}:", Artist[i])
    
#Track 357,384,411,442 are the same, while 1046,1074, 1101 are the same.

In [ ]:
for i in error_index:
    print(f"Track {i}:",Track_Name[i])
    print(f"Artist {i}:", Artist[i])
    
#Track 357,384,411,442 are the same, while 1046,1074, 1101 are the same.

In [30]:
# US21_feat=US21_feat.loc[(US21_feat['Track Name']!= " Ain't Shit ")&(US21_feat['Track Name']!=" We're Good ")]
error_index=[384,411,442,1074,1101]
updated_US21= US21_feat.drop(error_index)

updated_US21['Track Name'][357]='Aint Shit'
updated_US21['Track Name'][1046]='Were Good'

Track_Name= updated_US21['Track Name']
Artist= updated_US21['Artist']

# US21_feat['Track Name'][357]='Aint Shit'
# US21_feat['Track Name'][1046]='Were Good'
# Track_Name= US21_feat['Track Name']
# Artist= US21_feat['Artist']

In [28]:
track_info= do_request(Track_Name[1046], Artist[1046])
sp.audio_features(track_info['tracks']['items'][0]['uri'])[0]

{'danceability': 0.722,
 'energy': 0.588,
 'key': 6,
 'loudness': -5.932,
 'mode': 1,
 'speechiness': 0.0544,
 'acousticness': 0.0319,
 'instrumentalness': 0,
 'liveness': 0.183,
 'valence': 0.59,
 'tempo': 134.01,
 'type': 'audio_features',
 'id': '1diS6nkxMQc3wwC4G1j0bh',
 'uri': 'spotify:track:1diS6nkxMQc3wwC4G1j0bh',
 'track_href': 'https://api.spotify.com/v1/tracks/1diS6nkxMQc3wwC4G1j0bh',
 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/1diS6nkxMQc3wwC4G1j0bh',
 'duration_ms': 165507,
 'time_signature': 4}

In [31]:
features={}
error_index=[]

for i in range(len(Track_Name)):
    try:
        track_info= do_request(Track_Name[i], Artist[i])
        features.update({i:sp.audio_features(track_info['tracks']['items'][0]['uri'])[0]})

    except:
        error_index.append(i)
        
print("Error on:", error_index)

Error on: [384, 411, 442, 1074, 1101]

In [ ]:
features

In [ ]:
for i in error_index:
    print(f"Track {i}:",Track_Name[i])
    print(f"Artist {i}:", Artist[i])
    
#Track 357,384,411,442 are the same, while 1046,1074, 1101 are the same.

In [ ]:
features= pd.to_dataframe(features)
US21= pd.concat([US21_feat, features], axis=1)

In [ ]:
df_US20.columns